### ISSUE TITLE
Can you to add Claims support to your example?

### ISSUE THREAD

**Issue by P9avel** [LeaoSomogyi/poc-ocelot#5]
Hi, thank you for your work. I am want to use your solution for my task. Can you to help me and other users? Please 
1. convert example to .Net 6 and latest Ocelot version 12
2. can you prepare example with claim base authorization. For example i am want to use [Authorize("MyPolice")] attribute for some controller actions
I think with very hepled many peoples

**Comment by LeaoSomogyi** [comment]
@P9avel hello! I'm happy to knew my work helped someone :smile: 

In this example, Ocelot will repass the token to all service calls, so you just need to configure the `[Authorize("MyPolice")]` for each resource in order to validate if the user can access or not.

I will update the example applying some Policies, not sure how long it will take :sweat_smile:

**Comment by LeaoSomogyi** [comment]
@P9avel thanks for the Issue! I updated the project to .net 6.0 and create some policy example, just follow the instructions on readme.md and import the postman collection.

Hope it helps :smile:
